### ISSUE TITLE
Build testing and accuracy, performance benchmark framework

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/ristretto#10]
Previous work -
* https://github.com/dgryski/trifles/tree/master/cachetest
* https://github.com/dgraph-io/badger/tree/master/ristretto

**Comment by ben-manes** [comment]
Simulator:
https://github.com/ben-manes/caffeine/wiki/Simulator

**Comment by ben-manes** [comment]
Golang port of Caffeine’s benchmark
https://github.com/dgraph-io/benchmarks/blob/master/cachebench/cache_bench_test.go

**Comment by karlmcguire** [comment]
The benchmarking framework resides in the [bench](https://github.com/dgraph-io/ristretto/tree/master/bench) folder (for now).

Things to be added in order of priority, as per @ben-manes' [useful notes](https://github.com/dgraph-io/ristretto/pull/20#issuecomment-497557598) on this subject:

1. Mixed get/set workloads
2. Zipf key accesses
3. Sequential cost of insert / eviction
4. Trace formats: CORDA, LIRS, ARC

I'll look into Java's trace simulator and see if it will be easier to go-bind or loosely structure our implementation off of it.
