### ISSUE TITLE
Set up TeamCity

### ISSUE THREAD

**Issue by karlmcguire** [dgraph-io/ristretto#103]
Migrate away from Github actions and use something else as discussed.

**Comment by jarifibrahim** [comment]
Related to https://github.com/dgraph-io/ristretto/issues/121

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8709). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
