### ISSUE TITLE
Add option to serialize cache contents to disk for warm startup

### ISSUE THREAD

**Issue by karlmcguire** [dgraph-io/ristretto#105]
Requested by someone at GoSF meetup.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8710). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
