### ISSUE TITLE
KeyToHash possibly letting key interfaces escape to heap

### ISSUE THREAD

**Issue by karlmcguire** [dgraph-io/ristretto#107]
As brought up in the performance Gopher channel, since we're using `interface{}` for keys, [this call to `keyToHash`](https://github.com/dgraph-io/ristretto/blob/master/cache.go#L166) is probably letting the interface escape to heap.

Solution: switch over to `string` or `[]byte` for public API calls.

**Comment by martinmr** [comment]
@karlmcguire should the change be for keys or keys and values?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8711). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
