### ISSUE TITLE
add multidelete support. 

### ISSUE THREAD

**Issue by balajijinnah** [dgraph-io/ristretto#109]
Support multi delete.

Make Del as a vardic function to support delete.

**Comment by momilo** [comment]
I would be happy to implement this if you need an extra pair of hands.

**Comment by balajijinnah** [comment]
@momilo Feel free to take it.

**Comment by karlmcguire** [comment]
@balajijinnah @momilo As I mentioned to @manishrjain there will be no performance gains in adding a MultiDelete function until we move from a sharded map implementation (if we do). Based on experiments at https://github.com/karlmcguire/stress we've found that the fastest overall solution is the one we're currently using: a sharded hashmap. 

Therefore, for MultiDelete the fastest solution is indeed the simplest most idiomatic one:

```go
func (m *Map) MultiDel(keys []uint64) {
	for _, key := range keys {
		m.shards[key&shardMask].Del(key)
	}
}
```

This issue should be on hold until we change the underlying hashmap. For now, just call `Del` multiple times in a for loop.

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8413). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8419). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
