### ISSUE TITLE
keyhash and conflict all same

### ISSUE THREAD

**Issue by linger1216** [dgraph-io/ristretto#137]
assume Key A, Key B

A(keyHash) A(Confilct) equal B(keyHash) B(Confilct)

In this case, do I have to double check the value every time?

Thanks

**Comment by martinmr** [comment]
Depends on your keyToHash function but the following is true of the default keyToHash function.

For bytes, and integer types, the key hash is `uint64(k)` and the conflict key is `0`. So if the keys are different, so will be their hash.

For byte arrays and strings, the key hash is `memhash(k, uintptr(len(k)))` and the conflict hash is `xxhash.Sum64(k)`. memhash is implemented in the runtime library and xxhash is from this library 	"github.com/cespare/xxhash".

I don't know the details of each implementation but given that we use two different hashes that seem to have low collision rates, the chance of the two algorithms returning the same answer for two different keys is very low. I don't think you need to worry about it by checking the value every time.

**Comment by linger1216** [comment]
I understand, the probability is very, very small, but there is still the limiting case, thanks.
I have another question about expiration, I create a new issue. :)

**Comment by reyoung** [comment]
It seems that you can same an extra key in value, and manually check the key is same or not.
