### ISSUE TITLE
Prometheus metrics for memory usage in bytes

### ISSUE THREAD

**Issue by bzon** [dgraph-io/ristretto#140]
It would be really helpful if we expose this as a Prometheus metric.

**Comment by martinmr** [comment]
Yeah, not a bad idea to have the option to export this metric (and probably all the other ones) integrated with Prometheus. I'll look into it.

**Comment by bzon** [comment]
Cool! Probably look up opencensus (soon to be opentelemetry) so tracing can be enabled as well. 

If the Cache can be an interface, then it would be easier to just instrument metrics at the middleware level.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8713). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
