### ISSUE TITLE
Please publish a Release

### ISSUE THREAD

**Issue by alixMougenot** [dgraph-io/ristretto#141]
The current and only release is old. Go get will fetch this old version by default, without the TTL functionality. Go get will thus fetch a version that does not comply with the README.

Can you publish a release that matches the documentation?
Thank you.

**Comment by martinmr** [comment]
Duplicate of #95 

I'll try to get a new release (`v0.0.2` most likely) that has the TTL changes.

For now, you should be able to fix the version of ristretto to the latest commit timestamp.
