### ISSUE TITLE
Is this a storage bug?

### ISSUE THREAD

**Issue by linger1216** [dgraph-io/ristretto#149]
code in store.go

```
              by key
shardedMap   ------->    lockedMap
```

assume item1 and item2
item1:
key:        1,
conflict:   1,
value:      "val1",
expiration: time.Now().Add(60 * time.Millisecond),

item1:
key:        1,
conflict:   2,
value:      "val2",
expiration: time.Now().Add(180 * time.Millisecond),

```
step1: set item1
expirationMap: 
  buckets[1585036618][1] = 1
lockedMap: 
  data[1] = item1

step2: set item2
expirationMap: 
  1. del buckets[1585036618][1] = 1
  2. add buckets[1585036833][1] = 2

lockedMap: because conflict not equal so not change 
  data[1] = item1

now, item1 expiration change to item2 expiration value, but item1 is not change, why?
```

question:
I agree with two hashes to determine a unique value, but lockmap does use a hash value(key) to store items. 
ues one key to store item I think the same key probability is still very high?

many the different key, because the hash key is the same(the conflict different) cannot be updated
Is this a problem? Or is it a special design?

test case as below
```
func TestLockedMap_Lid(t *testing.T) {
	em := newExpirationMap()
	m := newLockedMap(em)

	m.Set(&item{
		key:        1,
		conflict:   1,
		value:      "val1",
		cost:       3,
		expiration: time.Now().Add(60 * time.Millisecond),
	})

	m.Set(&item{
		key:        1,
		conflict:   2,
		value:      "val2",
		cost:       3,
		expiration: time.Now().Add(160 * time.Millisecond),
	})

	fmt.Println(m.get(1, 2))
}
```

**Comment by martinmr** [comment]
Yes, it looks like we are writing to the expiration map before checking the conflict key. Thanks for bringing this up to my attention.
