### ISSUE TITLE
Broken images in the Readme

### ISSUE THREAD

**Issue by paskal** [dgraph-io/ristretto#155]
Readme has links to images like `https://raw.githubusercontent.com/karlmcguire/karlmcguire.com/master/docs/Hit%20Ratios%20-%20Search%20(ARC-S3).svg?sanitize=true` which are not working anymore, is it possible to upload these here and add them instead?

**Comment by danielmai** [comment]
Hey @paskal, thanks for letting us know. We'll get the benchmark charts back in the README. Not sure why there were hosted somewhere else to begin with.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8716). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
