### ISSUE TITLE
Standard lib includes maphash

### ISSUE THREAD

**Issue by masknu** [dgraph-io/ristretto#156]
It seems like golang standard library includes memhash in version 1.14.1.
The import path is "hash/maphash".
Didn't test it yet, perhaps it could replace memhash in the code.

**Comment by parasssh** [comment]
We will look at it.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8717). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
