### ISSUE TITLE
Refresh after write feature request

### ISSUE THREAD

**Issue by sanketpayghan** [dgraph-io/ristretto#159]
Caches like guava (java) has functionality to refresh cache values after write and after access by some time duration. 

Can we have something similar to it in ristretto?

**Comment by sanketpayghan** [comment]
If this is something can be done. I would like to work on it. Let me know.

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8423). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
