### ISSUE TITLE
There should be a test-only blocking mode

### ISSUE THREAD

**Issue by nes1983** [dgraph-io/ristretto#162]
The readme file shows that in order to test ristretto, one must use time.Sleep. As far as I understand, that isn't good software engineering practice. In fact, it's conceptually inherently a race condition. I understand it isn't the kind of race condition that can yield memory corruption. But still -- any test that relies on test.Sleep can fail if it misjudges how long an operation can take. 

I'd like to propose a test-only mode that makes the Set operation blocking, until the write has completed. With it, one can write more predictable, simpler unit test.

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8424). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
