### ISSUE TITLE
ristretto should investigate using the new go builtin hash functions

### ISSUE THREAD

**Issue by nes1983** [dgraph-io/ristretto#163]
The latest version of Go ships with a maphash package that's meant for exactly ristretto's kind of use case: https://golang.org/pkg/hash/maphash/. It's probably worth investigating if it can be used in order to get a speed boost.

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8425). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
