### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by erikdubbelboer** [dgraph-io/ristretto#164]
The last release was 112 days ago. Some useful commits have been merged into master since then. Maybe it's time for a new release?

Changes since the last version:
* 49dc42c Add Anurag as codeowner (#158) (Anurag)
* 7a3f2d3 z: use MemHashString and xxhash.Sum64String (#153) (Koichi Shiraishi)
* 9c31bb2 Check conflict key before updating expiration map. (#154) (Martin Martinez Rivera)
* 62cb731 Fix race condition in Cache.Clear (#133) (Martin Martinez Rivera)
* 9af1934 Docs and whitespace changes for readability. (#143) (Martin Martinez Rivera)

**Comment by jarifibrahim** [comment]
@anurags92 @martinmr we should do a new release of ristretto.

**Comment by martinmr** [comment]
Yeah, we can do one. Let's wait until #168 is merged and I'll create a new release.

**Comment by bt** [comment]
Just came across this library and want to use it in my production app -- seems like #168 is merged now, can we release a new version? 👼

**Comment by jarifibrahim** [comment]
@bt we'll do a release today unless @martinmr has any objections.

**Comment by bt** [comment]
> @bt we'll do a release today unless @martinmr has any objections.

Thank you 🙏

**Comment by bt** [comment]
Sorry for re-bumping this, just wanted to see if we can push out a new release. Thanks!

**Comment by anurags92** [comment]
Yes, will do. Friday was holiday for some of us. I guess it should be done today. Thanks for bumping!

**Comment by martinmr** [comment]
New release: https://github.com/dgraph-io/ristretto/releases/tag/v0.0.3
