### ISSUE TITLE
Question - Keys added and Keys evicted graphs are similar??

### ISSUE THREAD

**Issue by varun06** [dgraph-io/ristretto#165]
Hey Folks,

I am testing Ristretto in QA environment. I am still trying to understand few things. Once thing that I noticed, line for Keys Added and Keys Evicted are super close to each other. 

<img width="665" alt="Screen Shot 2020-06-26 at 10 05 49 AM" src="https://user-images.githubusercontent.com/1284070/85872081-e5670c00-b794-11ea-91b2-c3824d92cb33.png">

I have a feeling that I am doing something wrong here. 

Case size = 10gig

**Comment by jarifibrahim** [comment]
Hey @varun06, once the cache reaches the capacity (10 gigs) in this case, every new addition would try to make space for new insertions and so it would cause evictions.
Also, while inserting an item in the cache, you would set the `cost` param in the `cache.Set` call. Ensure that `cost` represents the correct cost of the item. If you set the cost of a single item as `10 GB`, ristretto will evict all the old data when this key is inserted.

**Comment by varun06** [comment]
Thanks a lot @jarifibrahim 

That make sense. I am going to find out more about our median/99p response times this week. I am still not clear about cache falling all the way down to 0(I hope that's not a restart...). But is that also normal?

**Comment by jarifibrahim** [comment]
>I am still not clear about cache falling all the way down to 0(I hope that's not a restart...)

@varun06 Do you mean you get 0 hits from ristretto?

**Comment by varun06** [comment]
Apologies, I am definitely seeing the hits. Also there was a restart it seems that cleared the cache ofc. 

At this point, I am trying to understand why our **keys added stats** is almost similar to **keys evicted stats**. Also added a stat to figure our the response size today.

**Comment by jarifibrahim** [comment]
@varun06 I could be wrong but I think the eviction would depend on your access pattern. if you're inserting data that never gets accessed and then new data is inserted, the old data will be evicted. Maybe look at the cache metrics (`cache.Metrics`) and see how your hits/misses are doing.

**Comment by varun06** [comment]
Yeah, that's how our current pattern for cache hits is looking like - 

<img width="1417" alt="Screen Shot 2020-06-29 at 11 34 56 AM" src="https://user-images.githubusercontent.com/1284070/86032227-9b805f00-b9fc-11ea-9bdb-e44286ac09f5.png">

BTW, this is just test env, if everything goes well, we are planning to deploy to a significant scale. 

This is how our get latency look after moving to ristretto - 

<img width="1419" alt="Screen Shot 2020-06-29 at 11 03 32 AM" src="https://user-images.githubusercontent.com/1284070/86032338-cf5b8480-b9fc-11ea-8ef8-c846a33e8d78.png">

**Comment by jarifibrahim** [comment]
@varun06 Maybe a bigger cache is what you need.

**Comment by varun06** [comment]
Yup, going to go to 50gig soon.

**Comment by minhaj-shakeel** [comment]
**GitHub Issues is being deprecated.**
 This issue has been moved to [link](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences. 

 <img src="https://github.com/dgraph-io/github-utils/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8426). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
