### ISSUE TITLE
 benchmark about gc or plan to reduce gc

### ISSUE THREAD

**Issue by someview** [dgraph-io/ristretto#322]
### Question.

Is there some benchmark result about gc，or plan to reduce gc for this memory cache db

**Comment by arjunsk** [comment]
@fengyeall111 " Ristretto currently does not do anything specific to reduce the GC effort of scanning through these key-values."

Reference: https://discuss.dgraph.io/t/introducing-ristretto-a-high-performance-go-cache-dgraph-blog/5102/6
