### ISSUE TITLE
How many bits tinyLFU uses to count access frequency?

### ISSUE THREAD

**Issue by Millione** [dgraph-io/ristretto#335]
I found the explanation difference between code comments and  README. It confuses me.

https://github.com/dgraph-io/ristretto/blob/3177d9c9520c37d36b18113be01fea6393f63860/policy.go#L366-L374

https://github.com/dgraph-io/ristretto/blob/3177d9c9520c37d36b18113be01fea6393f63860/README.md?plain=1#L19

**Comment by anurags92** [comment]
Hi @Millione Thanks for highlighting, we will take a look at this. Looks like a mismatch between the implementation and the docs. I have added it to our internal tracker, we will update you here. Thanks!
