### ISSUE TITLE
[QUESTION]: Ristretto hit ratio benchmark result

### ISSUE THREAD

**Issue by Yiling-J** [dgraph-io/ristretto#336]
### Question.

Run arc-s3 benchmark in https://github.com/dgraph-io/benchmarks, set MaxCost to 500000 and I got the following result:
```
name       , label         , go,  mop/s,  ns/op, ac, byt, hits    , misses  ,   ratio
ristretto  , hits-arc-s3   ,  0, ------, ------, --, ---, 00172676, 16235026,   1.05%
```
My question is about this 1.05% ratio, is this the real hit ratio? From the Ristretto README Benchmarks, the s3 hit ratio with 500000 capacity should be around 50%. 

I ask this because I'm developing a similar cache package using W-TinyLFU, I also write some benchmarks and Ristretto hit ratio in my benchmarks are all extreamly low, I think maybe my benchmarks are wrong, so I tried the official dgraph-io/benchmarks and ask here.

**Comment by Yiling-J** [comment]
hit ratio benchmark results of my package and ristretto:
https://github.com/Yiling-J/theine-go#hit-ratios

**Comment by phuslu** [comment]
Similar result in my linux server (oracle arm machine)

![image](https://github.com/dgraph-io/ristretto/assets/195836/c2af0425-3e00-4bfa-bac3-046814ed02d5)
