### ISSUE TITLE
[Non-hashed key values in Item]: onEvict should send the non hashed key values

### ISSUE THREAD

**Issue by yusuf-kh** [dgraph-io/ristretto#356]
### Have you tried Ristretto before this proposal? and did not find anything similar?

Yes

### What you wanted to do.

I want to know the value of the actual key in onEvict hook. However, after storing a key-value pair in ristretto cache, the onEvict method only returns the key's hash, and not its actual value.

Moreover, I do know I can provide my own hash algorithm, but I want to keep using ristretto's default hashing algorithm. Unfortunately, the Hash algorithm isn't a public method, so I can't use that.

**Comment by mangalaman93** [comment]
We do not store the key in ristretto, if you care about the key, you could store it in the value.
