### ISSUE TITLE
[BUG]: Can't use Google's uuid.UUID (a byte array rather than slice) as a key

### ISSUE THREAD

**Issue by pete-woods** [dgraph-io/ristretto#370]
### What version of Ristretto are you using?

e7380b4f3a4387dfa8d1223966a66f636422bf5f

### What version of Go are you using?

1.21.5

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

N/A

### What steps will reproduce the bug?

Try using a `uuid.UUID` from Google's UUID library as the key. You get an error about it not being a valid type, despite being a byte array under the hood. If you cast the uuid to a byte slice like `c.Set(myUUID[:])` it works.

It seems like the right type should relatively easily be addable here: https://github.com/dgraph-io/ristretto/blob/main/z/z.go#L43

**Comment by matthewmcneely** [comment]
This is probably by-design. Adding support for types not part of Go's "Basic types" would result in a pretty long switch statement, and add unneeded dependencies from hundreds of package. The `c.Set(id[:])` operation you describe is idiomatic in Ristretto.

**Comment by pete-woods** [comment]
I guess I thought a byte array was the same kind of "basic type" as byte slice.

**Comment by matthewmcneely** [comment]
Yeah, arrays and slices are distinct types in Go. The `type UUID [16][byte` that Google's lib defines is of the former type.

I'm closing this, if you think it's still a problem you can reopen.

**Comment by pete-woods** [comment]
If you're set on not adding arrays to that func, instead I think it'd improve the developer experience a fair bit to update the restriction on your generic type for key to limit to the set of types that are actually supported.

At the minute it's "any", which will happily accept a whole much of types you don't support. Then of course you get panics, which could have been caught at runtime.

**Comment by matthewmcneely** [comment]
I agree that would be an improvement. Feel free to submit a PR!
