### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by dezren39** [dgraph-io/ristretto#374]
### Question.

hi can you please tag a new release with the latest code in the main branch?

i hope to use the changes from https://github.com/dgraph-io/ristretto/pull/366

**Comment by jlelse** [comment]
This should not be stale.

**Comment by clayne11** [comment]
+1 last release was over 6 months ago. Can we get a new release of this package?

**Comment by mangalaman93** [comment]
closing the issue now that we have v0.2.0 is out.
