### ISSUE TITLE
Missing commits/PRs on main

### ISSUE THREAD

**Issue by stlava** [dgraph-io/ristretto#377]
### Question.

I found that a few PRs made back in 2022 were merged into `master` instead of `main` and now the two histories (and versions) differ. I didn't piece the timeline together but what I assume happened was a few PRs were opened against `master` and the repo changed default branches.

Specifically a race condition fixed in https://github.com/dgraph-io/ristretto/pull/294 got merged into `master` and never made it to `main`.

The way I found this was a project I'm working on uses `v0.0.0-20220403145359-8e850b710d6d` and I had trouble finding that hash version until it occurred to check the `master` branch which may have been default at the time.

**Comment by StarpTech** [comment]
Hi, any updates? We run into the same race condition and it would be very sad if we wouldn't find one to cherry pick the contributions.
