### ISSUE TITLE
Cache configuration checks should consider negative values for `NumCounters`/`MaxCost`/`BufferItems`

### ISSUE THREAD

**Issue by ankon** [dgraph-io/ristretto#378]
Found while reading through the code:
https://github.com/dgraph-io/ristretto/blob/c67e07994f911dbf42104f568c83a29830e88236/cache.go#L169-L174

The checks are fine, but given that these are `int64`s they could be <0 which the checks won't catch unless I'm missing something.

**Comment by zhaohaihang** [comment]
I also think that the aforementioned variables should be set to be greater than 0.  Because if the aforementioned variables are less than 0, it will cause the program to fail.  Since we're already performing checks, why not do it even better?

**Comment by mangalaman93** [comment]
Fixed by #410
