### ISSUE TITLE
[BUG]: <Title>Cannot correctly view a transparent png file, which is very long

### ISSUE THREAD

**Issue by KZ25T** [dgraph-io/ristretto#379]
### What version of Ristretto are you using?

0.13.1

### What version of Go are you using?

go1.22.2 linux/amd64

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

RAM: 32GB
CPU; intel core i7-1165G
OS: kali GNU/Linux (derived from debian), amd64

### What steps will reproduce the bug?

when I try to view a RGBA png file, which is very long (46585*72) and most pixels is transparent, it will show all pixels in transparent, no matter how I enarge it.

### Expected behavior and actual result.

Expected: I can view it correctly on visual studio code (after I enlarge it):
![image](https://github.com/dgraph-io/ristretto/assets/95907533/42fa6c1f-ccd9-4c56-b122-717b6fe77323)
Actual: I can't view it correctly on ristretto:
![image](https://github.com/dgraph-io/ristretto/assets/95907533/ee4d0d32-f158-4b19-9273-51d47371d827)
and the image is:
[
![img_a](https://github.com/dgraph-io/ristretto/assets/95907533/5080a21b-5b36-4d54-9700-b7d6a0b8424e)
](url)

and the base64 encode of the image (to avoid compressed and converted):

[image_base64.txt](https://github.com/dgraph-io/ristretto/files/15250181/image_base64.txt)

md5sum of the image(not base64 file): 4d1dcf96d59036c5e8ead35ce91187a5

### Additional information

Please forgive me for my poor English expression for my native language is not English. And I'll be apologise if any of my offensive behavior occured. Thanks for viewing my issue.

**Comment by mangalaman93** [comment]
This issue seems misplaced. Ristretto is an embedded cache and cannot be used for viewing images. I am gonna close it until more information is provided. Thank you
