### ISSUE TITLE
probably harmless, but the name is already in use by a software package

### ISSUE THREAD

**Issue by seebs** [dgraph-io/ristretto#4]
https://blog.xfce.org/2008/03/ristretto-a-lightweight-image-viewer/

not sure this matters, but i figure this is a much better time to point it out than a year from now would be.

**Comment by manishrjain** [comment]
I think we're good there. If you search for [ristretto cache] in Google, this repo shows up as the top result. Searching just for [ristretto] shows results for coffee.
