### ISSUE TITLE
[QUESTION]: Does doing a get on a key update its ttl ?

### ISSUE THREAD

**Issue by 0110G** [dgraph-io/ristretto#403]
### Question.

Does doing a cache.Get(k) on a key k update its ttl ?

**Comment by KMACEL** [comment]
@0110G Hello. No, it does not update.

**Comment by avadhut123pisal** [comment]
Is there any plan to support the dynamic TTL ?

**Comment by mangalaman93** [comment]
Could you elaborate your use case and what you mean by dynamic TTL?
