### ISSUE TITLE
[QUESTION]: Tests and documentation about Version 1.0.0

### ISSUE THREAD

**Issue by KMACEL** [dgraph-io/ristretto#404]
### Question.

Hi,

I use ristretto very actively in my projects. Thank you for this library. I would like to get information about the newly released 1.0.0 version. Is it stable enough? Have the tests been done? The document is still old. For this reason, I am not sure if I should migrate my system according to the new usage.

**Comment by mangalaman93** [comment]
We are considering releasing v2 and deprecate v1 all together . Beyond that, the API is stable, we are not planning to make any breaking changes. See here for more details https://github.com/dgraph-io/ristretto/issues/394
