### ISSUE TITLE
[BUG]: Retracted versions v1.0.0 and v1.0.1 with still active BadgerDB release depending on them

### ISSUE THREAD

**Issue by dkorunic** [dgraph-io/ristretto#413]
### What version of Ristretto are you using?

v1.0.0

### What version of Go are you using?

go1.23.2

### Have you tried reproducing the issue with the latest release?

None

### What is the hardware spec (RAM, CPU, OS)?

N/A.

### What steps will reproduce the bug?

Latest BadgerDB release [v4.3.1](https://github.com/dgraph-io/badger/releases/tag/v4.3.1) still depends on Ristretto `v1.0.0` that has been retracted [since](https://github.com/dgraph-io/ristretto/blob/v1.0.1/go.mod), causing errors on `go get -u`. IMO releases should be retracted only once there are no latest releases depending on them, meaning there are releases superseding retracted ones:

```
$ go get -u
go: warning: github.com/dgraph-io/ristretto@v1.0.0: retracted by module author: we retract v1.0.0 because v0.2.0 is not backwards compatible with v1.0.0.
go: to switch to the latest unretracted version, run:
	go get github.com/dgraph-io/ristretto@latest
```

In fact, this above will cause BadgerDB release to be downgraded from `v4.3.1` to `v4.3.0` as as consequence of Ristretto `v1.0.0` retraction.

**Comment by mangalaman93** [comment]
Hi @dkorunic , we are working on getting a new ristretto and a badger release out.

**Comment by dkorunic** [comment]
Thanks @mangalaman93. I am seeing new [Ristretto](https://github.com/dgraph-io/ristretto/releases/tag/v2.0.0) and [BadgerDB](https://github.com/dgraph-io/badger/releases/tag/v4.4.0) releases and I'm closing the issue as resolved.
