### ISSUE TITLE
Time aware LFU (windowing, temporary immunity)

### ISSUE THREAD

**Issue by andersfylling** [dgraph-io/ristretto#46]
Would you consider adding a time aware LFU, such that completely new entries can't have the probability of being evicted right after insertion? 

Eg. New entries are given a 1 minute time frame to become useful. Potentially increasing survival rates of fresh entries.

**Comment by karlmcguire** [comment]
Yes, we've experimented with different ways of calculating item value in the eviction process. One of which I've got my eye on is [Hyperbolic caching](https://dl.acm.org/citation.cfm?id=3154690.3154738), which lazily evaluates a hyperbolic function to derive item value. It would be easy to include `creation time` in the function and give items temporary eviction immunity.

We'll look into it more, thanks for the suggestion.

**Comment by ben-manes** [comment]
An admission window serves a similar purpose by delaying the evaluation until the item has been idle for a number of accesses. You might compare to that scheme (W-TinyLfu).

**Comment by andersfylling** [comment]
> An admission window serves a similar purpose by delaying the evaluation until the item has been idle for a number of accesses.

But will this allow increasing the LFU params of the delayed items?

**Comment by ben-manes** [comment]
It would allow the item to build up its frequency if used or be discarded if not. An LRU trace favors a larger delay, whereas an MRU trace favors a lower delay. Hyperbolic, without tinylfu, performs wildly across different traces (see our adaptivity paper),

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8706). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
