### ISSUE TITLE
Possible bug when processing items

### ISSUE THREAD

**Issue by marigonzes** [dgraph-io/ristretto#49]
I was reading through the code to see how you implemented "ristretto" and I came up to this line: https://github.com/dgraph-io/ristretto/blob/master/cache.go#L201.
```go
c.onEvict(item.key, item.val, item.cost)
```
I might be wrong, because I don't yet fully understand the code involved, but shouldn't it be:
```go
c.onEvict(victim.key, victim.val, victim.cost)
```

**Comment by karlmcguire** [comment]
Thanks, you're correct. It is fixed now.
