### ISSUE TITLE
Add basic working LRU Cache

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/ristretto#5]

**Comment by waseem18** [comment]
Hey @mangalaman93 

I've gone through `design.md` and would love to be a part of this project.

Can I start by working on this issue?

Thanks

**Comment by mangalaman93** [comment]
Hi Waseem. Thank you for your interest, there may be other people working on it.  I would suggest that you use this issue to keep us posted with your progress and have discussions so that other people can jump in too. Specifically, for this issue, we should just copy an existing LRU cache implementation. One is here https://github.com/hashicorp/golang-lru/tree/master/simplelru
