### ISSUE TITLE
TestRingLossy fails with drain error

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/ristretto#60]
`TestRingLossy` fails on master with drain error

Run
```
while go clean -testcache && go test -v -race -run='TestRingLossy' -timeout=1m; do :; done    
```
to reproduce the failure

```
=== RUN   TestRingLossy
--- FAIL: TestRingLossy (0.01s)
    ring_test.go:57: drain error
FAIL
exit status 1
FAIL	github.com/dgraph-io/ristretto	0.012s

```

https://github.com/dgraph-io/ristretto/blob/ae326c3348e84b72d4f9db6b0ccb2f3551a0ed3e/ring_test.go#L41-L59

**Comment by jarifibrahim** [comment]
https://github.com/dgraph-io/ristretto/blob/ae326c3348e84b72d4f9db6b0ccb2f3551a0ed3e/ring.go#L127-L132 uses sync.Pool(..) and sync.Pool is not guaranteed to return the objects that were inserted into it. 
When the test is run with `-race` flag, there are multiple ring strips created and hence none of them reach capacity.

**Comment by karlmcguire** [comment]
I see. We need another way to make sure `ringLossy` is draining properly even with the `-race` flag. The behavior we're seeing now is the correct behavior, it's just hard to test.

**Comment by jarifibrahim** [comment]
@karlmcguire I thought of doing something along similar lines. Do you mind sending a PR? I ran your snippet and I didn't see any failures after running the test for ~10m.
