### ISSUE TITLE
Add Tiny LFU Cache Admission Policy to Cache

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/ristretto#7]
Existing Implementation Reference: https://github.com/dgryski/go-tinylfu
Reference Paper: https://drive.google.com/file/d/1xW69zyULqcPf63A-cLdNsNOVrr8QygOr/view?usp=sharing

**Comment by ben-manes** [comment]
HashDoS protection:
https://github.com/ben-manes/caffeine/blob/91eec88be93f16549ce82dd2f17959fd8eba75dd/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L749-L773

CountMin4:
https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/FrequencySketch.java

W-TinyLfu (simulator):
https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/sketch/WindowTinyLfuPolicy.java

**Comment by ben-manes** [comment]
I'm not sure if @karlmcguire is involved in this effort, but he's been cranking out a nice looking implementation. Lots more to do (e.g. adaptivity) but fyi if disjoint work.

https://github.com/xba/tinylfu
