### ISSUE TITLE
Reduce GC overhead by using custom memory allocator

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/ristretto#8]

**Comment by ben-manes** [comment]
You will likely want to use a [SeqLock](https://en.wikipedia.org/wiki/Seqlock) when reading from / writing into the byte[] value. See Java's [StampedLock](https://github.com/AdoptOpenJDK/openjdk-jdk12u/blob/master/src/java.base/share/classes/java/util/concurrent/locks/StampedLock.java) API and internal algorithm notes for details

**Comment by sourabh1024** [comment]
I am planning to implement the following solution:

First, I am planning start with simple implementation of tcmalloc ( http://goog-perftools.sourceforge.net/doc/tcmalloc.html ) supporting small and large objects. However, the issue would be it would acquire lock on same class size to allocate memory. This might prove to be a point of contention.

We can reuse codes from golang memory allocator (https://golang.org/src/runtime/malloc.go)

**Comment by souvikhaldar** [comment]
What is the GC overhead here?

**Comment by souvikhaldar** [comment]
Are you planning on using *memory ballast* for reducing GC cycles?

**Comment by erikdubbelboer** [comment]
Memory ballast doesn't make sense for ristretto and if it would make sense it's still something the application should do by itself, not the library.

**Comment by erikdubbelboer** [comment]
A custom memory allocator doesn't make sense either seeing as ristretto only stores `interface{}`. You could build a library on top of ristretto that serializes all data you put in into `[]byte` that uses a custom allocator. But that's not the use case for ristretto. ristretto allows you to put in unseralizable data like channels as well.

**Comment by souvikhaldar** [comment]
My intention here is to understand what is the overhead of GC that this issue tries to reduce by the memory allocator. @mangalaman93 
When I see someone trying to reduce unnecessary GC cycles to keep heap memory size in check (which isn't much important) I can't help but suggest using **memory ballast**. Sure there needs to be fine-tuning further and it's better not to do it at the library level, but it's pretty much doable and helpful nonetheless. Also, I think it is going to be part of Go runtime soon (refer- https://github.com/golang/go/issues/23044) . @erikdubbelboer Can you suggest some alternative?

**Comment by erikdubbelboer** [comment]
I don't think this issue was created to reduce the amount of GC cycles. This is not something a custom memory allocator would change.

What this issue is about is that you want to have less pointers for the GC to check, so it runs faster. Using a custom memory allocator you can put everything in a `[]byte` so GC only has to check 1 pointer to the `[]byte` instead of all pointer to all objects.

**Comment by souvikhaldar** [comment]
I see. I would love to learn more about it. Is this what you are talking about? https://segment.com/blog/allocation-efficiency-in-high-performance-go-services/

If not, can you suggest some reading?

**Comment by erikdubbelboer** [comment]
Both [bigcache](https://github.com/allegro/bigcache#how-it-works) and [https://github.com/coocood/freecache#how-it-is-done](freecache) use different techniques to avoid having too many pointers.

**Comment by proyb6** [comment]
@erikdubbelboer I think you know VictoriaMetric have FastCache repo as well, is it a good example for reference reading?
https://github.com/ethereum/go-ethereum/pull/19971

**Comment by erikdubbelboer** [comment]
Yes fastcache is also very good. I didn't mention it because it has a bit more complex way to deal with lowering GC overhead.

**Comment by martinmr** [comment]
@mangalaman93 is this issue still relevant?

**Comment by mangalaman93** [comment]
I think so, because the way Ristretto stores data is all pointers. The more the data, GC effects are gonna be more and more visible.
