### ISSUE TITLE
add more cache implementations to benchmarking suite

### ISSUE THREAD

**Issue by karlmcguire** [dgraph-io/ristretto#83]
* https://github.com/jamiealquiza/bicache
* https://github.com/muesli/cache2go

**Comment by karlmcguire** [comment]
@muesli Is there a way to set a hard memory/item limit on cache2go?

**Comment by muesli** [comment]
I have been looking into that some years ago, but at least back then it wasn't really possible to achieve that reliably. For example if you'd use cache2go to store pointers, there wasn't a way to accurately calculate the underlying objects memory requirements.

I assume this is possible these days with the help of reflection?

**Comment by karlmcguire** [comment]
> I assume this is possible these days with the help of reflection?

Funny you should ask, it's currently being [discussed](https://github.com/golang/go/issues/34561#issuecomment-536886728). Ristretto just leaves it up to the user to determine the size of items and provide it when calling Set (as the `cost` parameter). We assume people storing pointers (slices, etc.) should have a reasonable guess of the underlying memory usage. 

The reason I ask is for our hit ratio benchmarking we try to ensure that all implementations have the same "size" as to not skew the numbers.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8707). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
