### ISSUE TITLE
Implement Adaptive Software Cache Management

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/ristretto#9]
Reference Paper: https://drive.google.com/file/d/1jfrH_xMxD7gRSIJYNJjiO-a2yt2fTD2J/view?usp=sharing

**Comment by ben-manes** [comment]
Simulation:
https://github.com/ben-manes/caffeine/tree/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/sketch/climbing

Library:
https://github.com/ben-manes/caffeine/blob/91eec88be93f16549ce82dd2f17959fd8eba75dd/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L943

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8704). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
