### ISSUE TITLE
Where are the releases?

### ISSUE THREAD

**Issue by andersfylling** [dgraph-io/ristretto#95]
I see you keep creating milestones and closing them, iterating the version. But where are the releases?

I'm sure you have your reasons, but would you be interested in doing git tags+github releases as well?

**Comment by erikdubbelboer** [comment]
Indeed tagging semver releases would be nice so people can see if there are API breaking changes or just bugfixes. It also look nicer in a go.mod file.

**Comment by martinmr** [comment]
I think there are a few items (mostly usability and integration items) that still need to be handled before releasing a stable 1.0 release. But I'll look into whether we can release a release candidate or something of the sort. For now, you can use the commit hash to keep the version of ristretto fixed. Not the prettiest solution but should be enough to prevent you from being affected by any API changes.

**Comment by lonnblad** [comment]
I believe it would be good to create v0.*.* releases as well, it would help projects that use Ristretto already at this stage, even though the project might not be mature enough for a v1 release.

Personally, I like the deprecation policy for the Open Census go project.
https://github.com/census-instrumentation/opencensus-go#deprecation-policy

**Comment by martinmr** [comment]
We just released a new pre-release v0.0.2 that includes the latest changes, including sets with TTL.
